name: 🚀 Coba

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 103.76.129.70
        username: coba@hanssu.my.id
        password: ujicoba
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
